# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/package.json') }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x


      - name: Install deps
        run: deno install
      
      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # TODO: enable fmt
      # - name: Verify formatting
      #   run: deno fmt --check

      # TODO: enable lint
      # - name: Run linter
      #   run: deno lint

      # TODO: add tests
      # - name: Run tests
      #   run: deno test -A
